---
- name: check current kernel release
  changed_when: no
  command: uname -r
  register: kernel_release
  tags:
    - kernel

- name: install linux kernel 4.9
  become: yes
  when: "'3.10.0' in kernel_release.stdout"
  yum:
    name: kernel-ml-4.9.0-1.el7.elrepo.x86_64
    enablerepo: elrepo
    state: present
  tags:
    - kernel

- name: check current default boot kernel
  become: yes
  changed_when: no
  command: grub2-editenv list
  register: default_kernel
  tags:
    - kernel

- name: make kernel 4.9 as default boot kernel
  become: yes
  when: "'3.10.0' in default_kernel.stdout"
  command: grub2-set-default 0
  tags:
    - kernel

#- name: update grub config used by EC2
#  become: yes
#  when: "'3.10.0' in default_kernel.stdout"
#  lineinfile:
#    dest: /boot/grub/menu.lst
#    regexp: '^default='
#    line: 'default=0'
#  tags:
#    - kernel

#- name: restart machine
#  when: "'3.10.0' in kernel_release.stdout"
#  shell: sleep 2 && shutdown -r now +1
#  async: 1
#  poll: 0
#  become: yes
#  ignore_errors: true
#  tags:
#    - kernel

#- name: waiting for server to come back
#  when: "'3.10.0' in kernel_release.stdout"
#  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
#  tags:
#    - kernel
