# Install a traefik load balancer on edge nodes backed by the consul service catalog.
# Run this playbook after running the core playbook # (sample.yml)

# CHECK SECURITY - when customizing you should leave this in. If you take it out
# and forget to specify security.yml, security could be turned off on components
# in your cluster!
- include: "{{ playbook_dir }}/../playbooks/check-requirements.yml"

- hosts: role=edge
  # vars:
  #   traefik_internal_consul_domain: match.your.dns.wildcard.entry.from.terraform
  roles:
    - traefik-internal
