---
# default is etc/utc in build 20141129 [http://cloud.centos.org/centos/7/images/]
- name: set timezone to etc/utc
  sudo: yes
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: yes

# add hosts to /etc/hosts
- name: configure hosts file
  sudo: yes
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
  tags:
    - common

- name: preserve hostname
  sudo: yes
  copy:
    src: 02_hostname.cfg
    dest: /etc/cloud/cloud.cfg.d/02_hostname.cfg
    owner: root
    group: root
    mode: 0644
  when: provider in cloud_init_providers
  tags:
    - common

- name: set persistent hostname
  sudo: yes
  copy:
    dest: /etc/hostname
    content: "{{ inventory_hostname }}"
    force: yes
    owner: root
    group: root
    mode: 0644
  tags:
    - common

- include: RedHat-install.yml
  when: ansible_os_family == 'RedHat'

- include: Debian-install.yml
  when: ansible_os_family == 'Debian'

- name: update setuptools and pip
  sudo: yes
  pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - name: pip
    - name: setuptools
  when: ansible_os_family == 'RedHat'

- name: disable requiretty in sudoers
  sudo: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: ^.+requiretty$
    line: "# Defaults	requiretty"

- name: configure selinux
  sudo: yes
  selinux:
    policy: "{{ selinux_policy }}"
    state: "{{ selinux_state }}"
  tags:
    - security
    - bootstrap
  when: ansible_os_family == 'RedHat'

- include: users.yml
  when: ansible_os_family == 'RedHat'
  
- include: ssh.yml

- include: RedHat-fail2ban.yml
  when: ansible_os_family == 'RedHat'

- include: Debian-fail2ban.yml
  when: ansible_os_family == 'Debian'

- name: ensure customized directory
  become: yes
  file:
    path: /opt/bin
    state: directory
    mode: 0755
