# add yum-utils if not already installed
- name: add yum-config-manager
  sudo: yes
  yum:
    name: yum-utils
  tags:
    - bootstrap

- name: increase timeouts in YUM
  sudo: yes
  shell: "yum-config-manager --save --setopt {{ item.option }}={{ item.value }}"
  with_items:
    - option: timeout
      value: 60.0
    - option: retries
      value: 30

- name: enable EPEL repo
  sudo: yes
  yum:
    name: epel-release
    state: latest
  tags:
    - bootstrap

- name: install system utilities
  sudo: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd-tools
    - nc
    - openssh
    - policycoreutils-python
    - libselinux-python
    - unzip
    - jq
    - java-1.8.0-openjdk
    - chrony
    - smlr
    - zookeepercli
    - NetworkManager
  tags:
    - bootstrap

- name: enable chronyd
  sudo: yes
  service:
    name: chronyd
    enabled: yes
    state: started

- name: disable firewalld
  sudo: yes
  service:
    name: firewalld
    enabled: false
    state: stopped
  register: command_result
  failed_when: "command_result|failed and 'No such file or directory' not in command_result.msg"
  ignore_errors: yes

- name: install pip
  sudo: yes
  yum:
    name: python-pip
    state: latest