---
- name: install dnsmasq dependencies
  sudo: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - dnsmasq
    - bind-utils
    - NetworkManager
  tags:
    - dnsmasq

- name: ensure customized config directory for dnsmasq
  become: yes
  file:
    path: /etc/dnsmasq.d
    state: directory
  tags:
    - dnsmasq

- name: setup consul dns config
  become: yes
  copy:
    src: 10-consul
    dest: /etc/dnsmasq.d/
    mode: 0755
  tags:
    - dnsmasq

- name: setup consul resolv.conf
  become: yes
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf.mantl-dns
    mode: 0755
  tags:
    - dnsmasq

- name: setup mantl-dns script
  become: yes
  copy:
    src: mantl-dns.sh
    dest: /opt/bin/mantl-dns.sh
    mode: 0755
  tags:
    - dnsmasq

- name: run mantl-dns script
  become: yes
  command: sh /opt/bin/mantl-dns.sh 
  tags:
    - dnsmasq


- name: configure dnsmasq for Kubernetes
  sudo: yes
  template:
    src: 20-kubernetes
    dest: /etc/dnsmasq.d/20-kubernetes
    mode: 0755
  when: cluster_name is defined
  notify:
    - restart dnsmasq
  tags:
    - dnsmasq

- meta: flush_handlers
