---
- name: download custom mantl-dns rpm
  get_url:
    url: http://ds-site-static-assets.s3.amazonaws.com/systems/mantl-dns-1.1.0-custombuild-ds.centos.x86_64.rpm  
    dest: /tmp/mantl-dns-1.1.0-custombuild-ds.centos.x86_64.rpm
  tags:
    - dnsmasq

- name: install mantl-dns
  become: yes
  yum:
    name: /tmp/mantl-dns-1.1.0-custombuild-ds.centos.x86_64.rpm
    state: installed
  tags:
    - dnsmasq
    - bootstrap

- name: remove consul from list of search domains
  sudo: yes
  command: sed -i'' 's/consul *//g' /etc/resolv.conf.masq
  tags:
    - dnsmasq

- name: remove localhost from list of resolvers
  sudo: yes
  lineinfile:
    dest: /etc/resolv.conf.masq
    regexp: nameserver 127.0.0.1
    state: absent
  tags:
    - dnsmasq

- name: configure dnsmasq for Kubernetes
  sudo: yes
  template:
    src: 20-kubernetes
    dest: /etc/dnsmasq.d/20-kubernetes
    mode: 0755
  when: cluster_name is defined
  notify:
    - restart dnsmasq
  tags:
    - dnsmasq

- meta: flush_handlers
